### ISSUE TITLE
Make Vector Speak more fun for Wayne

### ISSUE THREAD

**Issue by surlydev** [RamblingGeekUK/chatbot#10]
it would be much better if Vector had his own Twitch account, such as RamblingVector that people could open in the browser at twitch.tv/RamblingVector/chat (for example) and read the commands from there. Wayne would then genuinely react to him speaking without seeing the text message first.

An alternative would be to connect to Discord and take the commands from there. 

The twitch alternative channel idea will be easier to implement as it would just need Wayne to setup a Twitch account for Vector. Validate it. and then swap over the code to say which channel it is monitoring.

**Comment by RamblingGeekUK** [comment]
This has been partly implemented. 👍
